/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.sbi.StartUp.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the CapitalInf service. Represents a row in the &quot;SbiStartUp_CapitalInf&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.sbi.StartUp.model.impl.CapitalInfModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.sbi.StartUp.model.impl.CapitalInfImpl}.
 * </p>
 *
 * @author MAH97223
 * @see CapitalInf
 * @see com.sbi.StartUp.model.impl.CapitalInfImpl
 * @see com.sbi.StartUp.model.impl.CapitalInfModelImpl
 * @generated
 */
public interface CapitalInfModel extends BaseModel<CapitalInf> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a capital inf model instance should use the {@link CapitalInf} interface instead.
	 */

	/**
	 * Returns the primary key of this capital inf.
	 *
	 * @return the primary key of this capital inf
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this capital inf.
	 *
	 * @param primaryKey the primary key of this capital inf
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the inf ref ID of this capital inf.
	 *
	 * @return the inf ref ID of this capital inf
	 */
	public long getInfRefId();

	/**
	 * Sets the inf ref ID of this capital inf.
	 *
	 * @param InfRefId the inf ref ID of this capital inf
	 */
	public void setInfRefId(long InfRefId);

	/**
	 * Returns the create date of this capital inf.
	 *
	 * @return the create date of this capital inf
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this capital inf.
	 *
	 * @param createDate the create date of this capital inf
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this capital inf.
	 *
	 * @return the modified date of this capital inf
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this capital inf.
	 *
	 * @param modifiedDate the modified date of this capital inf
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the reg num of this capital inf.
	 *
	 * @return the reg num of this capital inf
	 */
	@AutoEscape
	public String getRegNum();

	/**
	 * Sets the reg num of this capital inf.
	 *
	 * @param RegNum the reg num of this capital inf
	 */
	public void setRegNum(String RegNum);

	/**
	 * Returns the cp_promoters_name of this capital inf.
	 *
	 * @return the cp_promoters_name of this capital inf
	 */
	@AutoEscape
	public String getCp_promoters_name();

	/**
	 * Sets the cp_promoters_name of this capital inf.
	 *
	 * @param cp_promoters_name the cp_promoters_name of this capital inf
	 */
	public void setCp_promoters_name(String cp_promoters_name);

	/**
	 * Returns the cp_promoters_address of this capital inf.
	 *
	 * @return the cp_promoters_address of this capital inf
	 */
	@AutoEscape
	public String getCp_promoters_address();

	/**
	 * Sets the cp_promoters_address of this capital inf.
	 *
	 * @param cp_promoters_address the cp_promoters_address of this capital inf
	 */
	public void setCp_promoters_address(String cp_promoters_address);

	/**
	 * Returns the cp_promoters_amount of this capital inf.
	 *
	 * @return the cp_promoters_amount of this capital inf
	 */
	@AutoEscape
	public String getCp_promoters_amount();

	/**
	 * Sets the cp_promoters_amount of this capital inf.
	 *
	 * @param cp_promoters_amount the cp_promoters_amount of this capital inf
	 */
	public void setCp_promoters_amount(String cp_promoters_amount);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(CapitalInf capitalInf);

	public int hashCode();

	public CacheModel<CapitalInf> toCacheModel();

	public CapitalInf toEscapedModel();

	public CapitalInf toUnescapedModel();

	public String toString();

	public String toXmlString();
}