/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.sbi.StartUp.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the SbiStartUp service. Represents a row in the &quot;SbiStartUp_SbiStartUp&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.sbi.StartUp.model.impl.SbiStartUpModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.sbi.StartUp.model.impl.SbiStartUpImpl}.
 * </p>
 *
 * @author MAH97223
 * @see SbiStartUp
 * @see com.sbi.StartUp.model.impl.SbiStartUpImpl
 * @see com.sbi.StartUp.model.impl.SbiStartUpModelImpl
 * @generated
 */
public interface SbiStartUpModel extends BaseModel<SbiStartUp> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a sbi start up model instance should use the {@link SbiStartUp} interface instead.
	 */

	/**
	 * Returns the primary key of this sbi start up.
	 *
	 * @return the primary key of this sbi start up
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this sbi start up.
	 *
	 * @param primaryKey the primary key of this sbi start up
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the regnum of this sbi start up.
	 *
	 * @return the regnum of this sbi start up
	 */
	@AutoEscape
	public String getRegnum();

	/**
	 * Sets the regnum of this sbi start up.
	 *
	 * @param regnum the regnum of this sbi start up
	 */
	public void setRegnum(String regnum);

	/**
	 * Returns the user name of this sbi start up.
	 *
	 * @return the user name of this sbi start up
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this sbi start up.
	 *
	 * @param userName the user name of this sbi start up
	 */
	public void setUserName(String userName);

	/**
	 * Returns the create date of this sbi start up.
	 *
	 * @return the create date of this sbi start up
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this sbi start up.
	 *
	 * @param createDate the create date of this sbi start up
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this sbi start up.
	 *
	 * @return the modified date of this sbi start up
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this sbi start up.
	 *
	 * @param modifiedDate the modified date of this sbi start up
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the registered_name of this sbi start up.
	 *
	 * @return the registered_name of this sbi start up
	 */
	@AutoEscape
	public String getRegistered_name();

	/**
	 * Sets the registered_name of this sbi start up.
	 *
	 * @param registered_name the registered_name of this sbi start up
	 */
	public void setRegistered_name(String registered_name);

	/**
	 * Returns the date_of_establishment of this sbi start up.
	 *
	 * @return the date_of_establishment of this sbi start up
	 */
	public Date getDate_of_establishment();

	/**
	 * Sets the date_of_establishment of this sbi start up.
	 *
	 * @param date_of_establishment the date_of_establishment of this sbi start up
	 */
	public void setDate_of_establishment(Date date_of_establishment);

	/**
	 * Returns the constitution of this sbi start up.
	 *
	 * @return the constitution of this sbi start up
	 */
	@AutoEscape
	public String getConstitution();

	/**
	 * Sets the constitution of this sbi start up.
	 *
	 * @param constitution the constitution of this sbi start up
	 */
	public void setConstitution(String constitution);

	/**
	 * Returns the address_line_1 of this sbi start up.
	 *
	 * @return the address_line_1 of this sbi start up
	 */
	@AutoEscape
	public String getAddress_line_1();

	/**
	 * Sets the address_line_1 of this sbi start up.
	 *
	 * @param address_line_1 the address_line_1 of this sbi start up
	 */
	public void setAddress_line_1(String address_line_1);

	/**
	 * Returns the address_line_2 of this sbi start up.
	 *
	 * @return the address_line_2 of this sbi start up
	 */
	@AutoEscape
	public String getAddress_line_2();

	/**
	 * Sets the address_line_2 of this sbi start up.
	 *
	 * @param address_line_2 the address_line_2 of this sbi start up
	 */
	public void setAddress_line_2(String address_line_2);

	/**
	 * Returns the address_landmark of this sbi start up.
	 *
	 * @return the address_landmark of this sbi start up
	 */
	@AutoEscape
	public String getAddress_landmark();

	/**
	 * Sets the address_landmark of this sbi start up.
	 *
	 * @param address_landmark the address_landmark of this sbi start up
	 */
	public void setAddress_landmark(String address_landmark);

	/**
	 * Returns the address_city of this sbi start up.
	 *
	 * @return the address_city of this sbi start up
	 */
	@AutoEscape
	public String getAddress_city();

	/**
	 * Sets the address_city of this sbi start up.
	 *
	 * @param address_city the address_city of this sbi start up
	 */
	public void setAddress_city(String address_city);

	/**
	 * Returns the address_pin of this sbi start up.
	 *
	 * @return the address_pin of this sbi start up
	 */
	@AutoEscape
	public String getAddress_pin();

	/**
	 * Sets the address_pin of this sbi start up.
	 *
	 * @param address_pin the address_pin of this sbi start up
	 */
	public void setAddress_pin(String address_pin);

	/**
	 * Returns the address_state of this sbi start up.
	 *
	 * @return the address_state of this sbi start up
	 */
	@AutoEscape
	public String getAddress_state();

	/**
	 * Sets the address_state of this sbi start up.
	 *
	 * @param address_state the address_state of this sbi start up
	 */
	public void setAddress_state(String address_state);

	/**
	 * Returns the corporate_email of this sbi start up.
	 *
	 * @return the corporate_email of this sbi start up
	 */
	@AutoEscape
	public String getCorporate_email();

	/**
	 * Sets the corporate_email of this sbi start up.
	 *
	 * @param corporate_email the corporate_email of this sbi start up
	 */
	public void setCorporate_email(String corporate_email);

	/**
	 * Returns the corporate_website of this sbi start up.
	 *
	 * @return the corporate_website of this sbi start up
	 */
	@AutoEscape
	public String getCorporate_website();

	/**
	 * Sets the corporate_website of this sbi start up.
	 *
	 * @param corporate_website the corporate_website of this sbi start up
	 */
	public void setCorporate_website(String corporate_website);

	/**
	 * Returns the initial_founders of this sbi start up.
	 *
	 * @return the initial_founders of this sbi start up
	 */
	@AutoEscape
	public String getInitial_founders();

	/**
	 * Sets the initial_founders of this sbi start up.
	 *
	 * @param initial_founders the initial_founders of this sbi start up
	 */
	public void setInitial_founders(String initial_founders);

	/**
	 * Returns the current_promoters_name of this sbi start up.
	 *
	 * @return the current_promoters_name of this sbi start up
	 */
	@AutoEscape
	public String getCurrent_promoters_name();

	/**
	 * Sets the current_promoters_name of this sbi start up.
	 *
	 * @param current_promoters_name the current_promoters_name of this sbi start up
	 */
	public void setCurrent_promoters_name(String current_promoters_name);

	/**
	 * Returns the noofemp of this sbi start up.
	 *
	 * @return the noofemp of this sbi start up
	 */
	@AutoEscape
	public String getNoofemp();

	/**
	 * Sets the noofemp of this sbi start up.
	 *
	 * @param noofemp the noofemp of this sbi start up
	 */
	public void setNoofemp(String noofemp);

	/**
	 * Returns the description_of_product of this sbi start up.
	 *
	 * @return the description_of_product of this sbi start up
	 */
	@AutoEscape
	public String getDescription_of_product();

	/**
	 * Sets the description_of_product of this sbi start up.
	 *
	 * @param description_of_product the description_of_product of this sbi start up
	 */
	public void setDescription_of_product(String description_of_product);

	/**
	 * Returns the initial_capital of this sbi start up.
	 *
	 * @return the initial_capital of this sbi start up
	 */
	@AutoEscape
	public String getInitial_capital();

	/**
	 * Sets the initial_capital of this sbi start up.
	 *
	 * @param initial_capital the initial_capital of this sbi start up
	 */
	public void setInitial_capital(String initial_capital);

	/**
	 * Returns the monetary_value of this sbi start up.
	 *
	 * @return the monetary_value of this sbi start up
	 */
	@AutoEscape
	public String getMonetary_value();

	/**
	 * Sets the monetary_value of this sbi start up.
	 *
	 * @param monetary_value the monetary_value of this sbi start up
	 */
	public void setMonetary_value(String monetary_value);

	/**
	 * Returns the business_model of this sbi start up.
	 *
	 * @return the business_model of this sbi start up
	 */
	@AutoEscape
	public String getBusiness_model();

	/**
	 * Sets the business_model of this sbi start up.
	 *
	 * @param business_model the business_model of this sbi start up
	 */
	public void setBusiness_model(String business_model);

	/**
	 * Returns the current_capital of this sbi start up.
	 *
	 * @return the current_capital of this sbi start up
	 */
	@AutoEscape
	public String getCurrent_capital();

	/**
	 * Sets the current_capital of this sbi start up.
	 *
	 * @param current_capital the current_capital of this sbi start up
	 */
	public void setCurrent_capital(String current_capital);

	/**
	 * Returns the capital_infusion of this sbi start up.
	 *
	 * @return the capital_infusion of this sbi start up
	 */
	@AutoEscape
	public String getCapital_infusion();

	/**
	 * Sets the capital_infusion of this sbi start up.
	 *
	 * @param capital_infusion the capital_infusion of this sbi start up
	 */
	public void setCapital_infusion(String capital_infusion);

	/**
	 * Returns the loans_availed of this sbi start up.
	 *
	 * @return the loans_availed of this sbi start up
	 */
	@AutoEscape
	public String getLoans_availed();

	/**
	 * Sets the loans_availed of this sbi start up.
	 *
	 * @param Loans_availed the loans_availed of this sbi start up
	 */
	public void setLoans_availed(String Loans_availed);

	/**
	 * Returns the valuer_name of this sbi start up.
	 *
	 * @return the valuer_name of this sbi start up
	 */
	@AutoEscape
	public String getValuer_name();

	/**
	 * Sets the valuer_name of this sbi start up.
	 *
	 * @param valuer_name the valuer_name of this sbi start up
	 */
	public void setValuer_name(String valuer_name);

	/**
	 * Returns the valuation_date of this sbi start up.
	 *
	 * @return the valuation_date of this sbi start up
	 */
	public Date getValuation_date();

	/**
	 * Sets the valuation_date of this sbi start up.
	 *
	 * @param valuation_date the valuation_date of this sbi start up
	 */
	public void setValuation_date(Date valuation_date);

	/**
	 * Returns the valuation_amount_rs of this sbi start up.
	 *
	 * @return the valuation_amount_rs of this sbi start up
	 */
	@AutoEscape
	public String getValuation_amount_rs();

	/**
	 * Sets the valuation_amount_rs of this sbi start up.
	 *
	 * @param valuation_amount_rs the valuation_amount_rs of this sbi start up
	 */
	public void setValuation_amount_rs(String valuation_amount_rs);

	/**
	 * Returns the loan_avail_source of this sbi start up.
	 *
	 * @return the loan_avail_source of this sbi start up
	 */
	@AutoEscape
	public String getLoan_avail_source();

	/**
	 * Sets the loan_avail_source of this sbi start up.
	 *
	 * @param loan_avail_source the loan_avail_source of this sbi start up
	 */
	public void setLoan_avail_source(String loan_avail_source);

	/**
	 * Returns the loan_avail_rs of this sbi start up.
	 *
	 * @return the loan_avail_rs of this sbi start up
	 */
	@AutoEscape
	public String getLoan_avail_rs();

	/**
	 * Sets the loan_avail_rs of this sbi start up.
	 *
	 * @param loan_avail_rs the loan_avail_rs of this sbi start up
	 */
	public void setLoan_avail_rs(String loan_avail_rs);

	/**
	 * Returns the gross_revenue_year1 of this sbi start up.
	 *
	 * @return the gross_revenue_year1 of this sbi start up
	 */
	@AutoEscape
	public String getGross_revenue_year1();

	/**
	 * Sets the gross_revenue_year1 of this sbi start up.
	 *
	 * @param gross_revenue_year1 the gross_revenue_year1 of this sbi start up
	 */
	public void setGross_revenue_year1(String gross_revenue_year1);

	/**
	 * Returns the gross_revenue_rs1 of this sbi start up.
	 *
	 * @return the gross_revenue_rs1 of this sbi start up
	 */
	@AutoEscape
	public String getGross_revenue_rs1();

	/**
	 * Sets the gross_revenue_rs1 of this sbi start up.
	 *
	 * @param gross_revenue_rs1 the gross_revenue_rs1 of this sbi start up
	 */
	public void setGross_revenue_rs1(String gross_revenue_rs1);

	/**
	 * Returns the gross_revenue_year2 of this sbi start up.
	 *
	 * @return the gross_revenue_year2 of this sbi start up
	 */
	@AutoEscape
	public String getGross_revenue_year2();

	/**
	 * Sets the gross_revenue_year2 of this sbi start up.
	 *
	 * @param gross_revenue_year2 the gross_revenue_year2 of this sbi start up
	 */
	public void setGross_revenue_year2(String gross_revenue_year2);

	/**
	 * Returns the gross_revenue_rs2 of this sbi start up.
	 *
	 * @return the gross_revenue_rs2 of this sbi start up
	 */
	@AutoEscape
	public String getGross_revenue_rs2();

	/**
	 * Sets the gross_revenue_rs2 of this sbi start up.
	 *
	 * @param gross_revenue_rs2 the gross_revenue_rs2 of this sbi start up
	 */
	public void setGross_revenue_rs2(String gross_revenue_rs2);

	/**
	 * Returns the gross_revenue_year3 of this sbi start up.
	 *
	 * @return the gross_revenue_year3 of this sbi start up
	 */
	@AutoEscape
	public String getGross_revenue_year3();

	/**
	 * Sets the gross_revenue_year3 of this sbi start up.
	 *
	 * @param gross_revenue_year3 the gross_revenue_year3 of this sbi start up
	 */
	public void setGross_revenue_year3(String gross_revenue_year3);

	/**
	 * Returns the gross_revenue_rs3 of this sbi start up.
	 *
	 * @return the gross_revenue_rs3 of this sbi start up
	 */
	@AutoEscape
	public String getGross_revenue_rs3();

	/**
	 * Sets the gross_revenue_rs3 of this sbi start up.
	 *
	 * @param gross_revenue_rs3 the gross_revenue_rs3 of this sbi start up
	 */
	public void setGross_revenue_rs3(String gross_revenue_rs3);

	/**
	 * Returns the ebidta_year1 of this sbi start up.
	 *
	 * @return the ebidta_year1 of this sbi start up
	 */
	@AutoEscape
	public String getEbidta_year1();

	/**
	 * Sets the ebidta_year1 of this sbi start up.
	 *
	 * @param ebidta_year1 the ebidta_year1 of this sbi start up
	 */
	public void setEbidta_year1(String ebidta_year1);

	/**
	 * Returns the ebidta_rs1 of this sbi start up.
	 *
	 * @return the ebidta_rs1 of this sbi start up
	 */
	@AutoEscape
	public String getEbidta_rs1();

	/**
	 * Sets the ebidta_rs1 of this sbi start up.
	 *
	 * @param ebidta_rs1 the ebidta_rs1 of this sbi start up
	 */
	public void setEbidta_rs1(String ebidta_rs1);

	/**
	 * Returns the ebidta_year2 of this sbi start up.
	 *
	 * @return the ebidta_year2 of this sbi start up
	 */
	@AutoEscape
	public String getEbidta_year2();

	/**
	 * Sets the ebidta_year2 of this sbi start up.
	 *
	 * @param ebidta_year2 the ebidta_year2 of this sbi start up
	 */
	public void setEbidta_year2(String ebidta_year2);

	/**
	 * Returns the ebidta_rs2 of this sbi start up.
	 *
	 * @return the ebidta_rs2 of this sbi start up
	 */
	@AutoEscape
	public String getEbidta_rs2();

	/**
	 * Sets the ebidta_rs2 of this sbi start up.
	 *
	 * @param ebidta_rs2 the ebidta_rs2 of this sbi start up
	 */
	public void setEbidta_rs2(String ebidta_rs2);

	/**
	 * Returns the ebidta_year3 of this sbi start up.
	 *
	 * @return the ebidta_year3 of this sbi start up
	 */
	@AutoEscape
	public String getEbidta_year3();

	/**
	 * Sets the ebidta_year3 of this sbi start up.
	 *
	 * @param ebidta_year3 the ebidta_year3 of this sbi start up
	 */
	public void setEbidta_year3(String ebidta_year3);

	/**
	 * Returns the ebidta_rs3 of this sbi start up.
	 *
	 * @return the ebidta_rs3 of this sbi start up
	 */
	@AutoEscape
	public String getEbidta_rs3();

	/**
	 * Sets the ebidta_rs3 of this sbi start up.
	 *
	 * @param ebidta_rs3 the ebidta_rs3 of this sbi start up
	 */
	public void setEbidta_rs3(String ebidta_rs3);

	/**
	 * Returns the gross_revenue_projected_year1 of this sbi start up.
	 *
	 * @return the gross_revenue_projected_year1 of this sbi start up
	 */
	@AutoEscape
	public String getGross_revenue_projected_year1();

	/**
	 * Sets the gross_revenue_projected_year1 of this sbi start up.
	 *
	 * @param gross_revenue_projected_year1 the gross_revenue_projected_year1 of this sbi start up
	 */
	public void setGross_revenue_projected_year1(
		String gross_revenue_projected_year1);

	/**
	 * Returns the projected_revenue_rs1 of this sbi start up.
	 *
	 * @return the projected_revenue_rs1 of this sbi start up
	 */
	@AutoEscape
	public String getProjected_revenue_rs1();

	/**
	 * Sets the projected_revenue_rs1 of this sbi start up.
	 *
	 * @param projected_revenue_rs1 the projected_revenue_rs1 of this sbi start up
	 */
	public void setProjected_revenue_rs1(String projected_revenue_rs1);

	/**
	 * Returns the gross_revenue_projected_year2 of this sbi start up.
	 *
	 * @return the gross_revenue_projected_year2 of this sbi start up
	 */
	@AutoEscape
	public String getGross_revenue_projected_year2();

	/**
	 * Sets the gross_revenue_projected_year2 of this sbi start up.
	 *
	 * @param gross_revenue_projected_year2 the gross_revenue_projected_year2 of this sbi start up
	 */
	public void setGross_revenue_projected_year2(
		String gross_revenue_projected_year2);

	/**
	 * Returns the projected_revenue_rs2 of this sbi start up.
	 *
	 * @return the projected_revenue_rs2 of this sbi start up
	 */
	@AutoEscape
	public String getProjected_revenue_rs2();

	/**
	 * Sets the projected_revenue_rs2 of this sbi start up.
	 *
	 * @param projected_revenue_rs2 the projected_revenue_rs2 of this sbi start up
	 */
	public void setProjected_revenue_rs2(String projected_revenue_rs2);

	/**
	 * Returns the gross_revenue_projected_year3 of this sbi start up.
	 *
	 * @return the gross_revenue_projected_year3 of this sbi start up
	 */
	@AutoEscape
	public String getGross_revenue_projected_year3();

	/**
	 * Sets the gross_revenue_projected_year3 of this sbi start up.
	 *
	 * @param gross_revenue_projected_year3 the gross_revenue_projected_year3 of this sbi start up
	 */
	public void setGross_revenue_projected_year3(
		String gross_revenue_projected_year3);

	/**
	 * Returns the projected_revenue_rs3 of this sbi start up.
	 *
	 * @return the projected_revenue_rs3 of this sbi start up
	 */
	@AutoEscape
	public String getProjected_revenue_rs3();

	/**
	 * Sets the projected_revenue_rs3 of this sbi start up.
	 *
	 * @param projected_revenue_rs3 the projected_revenue_rs3 of this sbi start up
	 */
	public void setProjected_revenue_rs3(String projected_revenue_rs3);

	/**
	 * Returns the projected_ebidta_year1 of this sbi start up.
	 *
	 * @return the projected_ebidta_year1 of this sbi start up
	 */
	@AutoEscape
	public String getProjected_ebidta_year1();

	/**
	 * Sets the projected_ebidta_year1 of this sbi start up.
	 *
	 * @param projected_ebidta_year1 the projected_ebidta_year1 of this sbi start up
	 */
	public void setProjected_ebidta_year1(String projected_ebidta_year1);

	/**
	 * Returns the projected_ebidta_rs1 of this sbi start up.
	 *
	 * @return the projected_ebidta_rs1 of this sbi start up
	 */
	@AutoEscape
	public String getProjected_ebidta_rs1();

	/**
	 * Sets the projected_ebidta_rs1 of this sbi start up.
	 *
	 * @param projected_ebidta_rs1 the projected_ebidta_rs1 of this sbi start up
	 */
	public void setProjected_ebidta_rs1(String projected_ebidta_rs1);

	/**
	 * Returns the projected_ebidta_year2 of this sbi start up.
	 *
	 * @return the projected_ebidta_year2 of this sbi start up
	 */
	@AutoEscape
	public String getProjected_ebidta_year2();

	/**
	 * Sets the projected_ebidta_year2 of this sbi start up.
	 *
	 * @param projected_ebidta_year2 the projected_ebidta_year2 of this sbi start up
	 */
	public void setProjected_ebidta_year2(String projected_ebidta_year2);

	/**
	 * Returns the projected_ebidta_rs2 of this sbi start up.
	 *
	 * @return the projected_ebidta_rs2 of this sbi start up
	 */
	@AutoEscape
	public String getProjected_ebidta_rs2();

	/**
	 * Sets the projected_ebidta_rs2 of this sbi start up.
	 *
	 * @param projected_ebidta_rs2 the projected_ebidta_rs2 of this sbi start up
	 */
	public void setProjected_ebidta_rs2(String projected_ebidta_rs2);

	/**
	 * Returns the projected_ebidta_year3 of this sbi start up.
	 *
	 * @return the projected_ebidta_year3 of this sbi start up
	 */
	@AutoEscape
	public String getProjected_ebidta_year3();

	/**
	 * Sets the projected_ebidta_year3 of this sbi start up.
	 *
	 * @param projected_ebidta_year3 the projected_ebidta_year3 of this sbi start up
	 */
	public void setProjected_ebidta_year3(String projected_ebidta_year3);

	/**
	 * Returns the projected_ebidta_rs3 of this sbi start up.
	 *
	 * @return the projected_ebidta_rs3 of this sbi start up
	 */
	@AutoEscape
	public String getProjected_ebidta_rs3();

	/**
	 * Sets the projected_ebidta_rs3 of this sbi start up.
	 *
	 * @param projected_ebidta_rs3 the projected_ebidta_rs3 of this sbi start up
	 */
	public void setProjected_ebidta_rs3(String projected_ebidta_rs3);

	/**
	 * Returns the projected_net_profit_year1 of this sbi start up.
	 *
	 * @return the projected_net_profit_year1 of this sbi start up
	 */
	@AutoEscape
	public String getProjected_net_profit_year1();

	/**
	 * Sets the projected_net_profit_year1 of this sbi start up.
	 *
	 * @param projected_net_profit_year1 the projected_net_profit_year1 of this sbi start up
	 */
	public void setProjected_net_profit_year1(String projected_net_profit_year1);

	/**
	 * Returns the projected_net_profit_rs1 of this sbi start up.
	 *
	 * @return the projected_net_profit_rs1 of this sbi start up
	 */
	@AutoEscape
	public String getProjected_net_profit_rs1();

	/**
	 * Sets the projected_net_profit_rs1 of this sbi start up.
	 *
	 * @param projected_net_profit_rs1 the projected_net_profit_rs1 of this sbi start up
	 */
	public void setProjected_net_profit_rs1(String projected_net_profit_rs1);

	/**
	 * Returns the projected_net_profit_year2 of this sbi start up.
	 *
	 * @return the projected_net_profit_year2 of this sbi start up
	 */
	@AutoEscape
	public String getProjected_net_profit_year2();

	/**
	 * Sets the projected_net_profit_year2 of this sbi start up.
	 *
	 * @param projected_net_profit_year2 the projected_net_profit_year2 of this sbi start up
	 */
	public void setProjected_net_profit_year2(String projected_net_profit_year2);

	/**
	 * Returns the projected_net_profit_rs2 of this sbi start up.
	 *
	 * @return the projected_net_profit_rs2 of this sbi start up
	 */
	@AutoEscape
	public String getProjected_net_profit_rs2();

	/**
	 * Sets the projected_net_profit_rs2 of this sbi start up.
	 *
	 * @param projected_net_profit_rs2 the projected_net_profit_rs2 of this sbi start up
	 */
	public void setProjected_net_profit_rs2(String projected_net_profit_rs2);

	/**
	 * Returns the projected_net_profit_year3 of this sbi start up.
	 *
	 * @return the projected_net_profit_year3 of this sbi start up
	 */
	@AutoEscape
	public String getProjected_net_profit_year3();

	/**
	 * Sets the projected_net_profit_year3 of this sbi start up.
	 *
	 * @param projected_net_profit_year3 the projected_net_profit_year3 of this sbi start up
	 */
	public void setProjected_net_profit_year3(String projected_net_profit_year3);

	/**
	 * Returns the projected_net_profit_rs3 of this sbi start up.
	 *
	 * @return the projected_net_profit_rs3 of this sbi start up
	 */
	@AutoEscape
	public String getProjected_net_profit_rs3();

	/**
	 * Sets the projected_net_profit_rs3 of this sbi start up.
	 *
	 * @param projected_net_profit_rs3 the projected_net_profit_rs3 of this sbi start up
	 */
	public void setProjected_net_profit_rs3(String projected_net_profit_rs3);

	/**
	 * Returns the net_profit_year1 of this sbi start up.
	 *
	 * @return the net_profit_year1 of this sbi start up
	 */
	@AutoEscape
	public String getNet_profit_year1();

	/**
	 * Sets the net_profit_year1 of this sbi start up.
	 *
	 * @param net_profit_year1 the net_profit_year1 of this sbi start up
	 */
	public void setNet_profit_year1(String net_profit_year1);

	/**
	 * Returns the net_profit_rs1 of this sbi start up.
	 *
	 * @return the net_profit_rs1 of this sbi start up
	 */
	@AutoEscape
	public String getNet_profit_rs1();

	/**
	 * Sets the net_profit_rs1 of this sbi start up.
	 *
	 * @param net_profit_rs1 the net_profit_rs1 of this sbi start up
	 */
	public void setNet_profit_rs1(String net_profit_rs1);

	/**
	 * Returns the net_profit_year2 of this sbi start up.
	 *
	 * @return the net_profit_year2 of this sbi start up
	 */
	@AutoEscape
	public String getNet_profit_year2();

	/**
	 * Sets the net_profit_year2 of this sbi start up.
	 *
	 * @param net_profit_year2 the net_profit_year2 of this sbi start up
	 */
	public void setNet_profit_year2(String net_profit_year2);

	/**
	 * Returns the net_profit_rs2 of this sbi start up.
	 *
	 * @return the net_profit_rs2 of this sbi start up
	 */
	@AutoEscape
	public String getNet_profit_rs2();

	/**
	 * Sets the net_profit_rs2 of this sbi start up.
	 *
	 * @param net_profit_rs2 the net_profit_rs2 of this sbi start up
	 */
	public void setNet_profit_rs2(String net_profit_rs2);

	/**
	 * Returns the net_profit_year3 of this sbi start up.
	 *
	 * @return the net_profit_year3 of this sbi start up
	 */
	@AutoEscape
	public String getNet_profit_year3();

	/**
	 * Sets the net_profit_year3 of this sbi start up.
	 *
	 * @param net_profit_year3 the net_profit_year3 of this sbi start up
	 */
	public void setNet_profit_year3(String net_profit_year3);

	/**
	 * Returns the net_profit_rs3 of this sbi start up.
	 *
	 * @return the net_profit_rs3 of this sbi start up
	 */
	@AutoEscape
	public String getNet_profit_rs3();

	/**
	 * Sets the net_profit_rs3 of this sbi start up.
	 *
	 * @param net_profit_rs3 the net_profit_rs3 of this sbi start up
	 */
	public void setNet_profit_rs3(String net_profit_rs3);

	/**
	 * Returns the financial_bank_engagement of this sbi start up.
	 *
	 * @return the financial_bank_engagement of this sbi start up
	 */
	@AutoEscape
	public String getFinancial_bank_engagement();

	/**
	 * Sets the financial_bank_engagement of this sbi start up.
	 *
	 * @param financial_bank_engagement the financial_bank_engagement of this sbi start up
	 */
	public void setFinancial_bank_engagement(String financial_bank_engagement);

	/**
	 * Returns the financial_assistance of this sbi start up.
	 *
	 * @return the financial_assistance of this sbi start up
	 */
	@AutoEscape
	public String getFinancial_assistance();

	/**
	 * Sets the financial_assistance of this sbi start up.
	 *
	 * @param financial_assistance the financial_assistance of this sbi start up
	 */
	public void setFinancial_assistance(String financial_assistance);

	/**
	 * Returns the financial_assi_purp of this sbi start up.
	 *
	 * @return the financial_assi_purp of this sbi start up
	 */
	@AutoEscape
	public String getFinancial_assi_purp();

	/**
	 * Sets the financial_assi_purp of this sbi start up.
	 *
	 * @param financial_assi_purp the financial_assi_purp of this sbi start up
	 */
	public void setFinancial_assi_purp(String financial_assi_purp);

	/**
	 * Returns the agreeable_process of this sbi start up.
	 *
	 * @return the agreeable_process of this sbi start up
	 */
	@AutoEscape
	public String getAgreeable_process();

	/**
	 * Sets the agreeable_process of this sbi start up.
	 *
	 * @param agreeable_process the agreeable_process of this sbi start up
	 */
	public void setAgreeable_process(String agreeable_process);

	/**
	 * Returns the gsr_department of this sbi start up.
	 *
	 * @return the gsr_department of this sbi start up
	 */
	@AutoEscape
	public String getGsr_department();

	/**
	 * Sets the gsr_department of this sbi start up.
	 *
	 * @param gsr_department the gsr_department of this sbi start up
	 */
	public void setGsr_department(String gsr_department);

	/**
	 * Returns the startupindia of this sbi start up.
	 *
	 * @return the startupindia of this sbi start up
	 */
	@AutoEscape
	public String getStartupindia();

	/**
	 * Sets the startupindia of this sbi start up.
	 *
	 * @param startupindia the startupindia of this sbi start up
	 */
	public void setStartupindia(String startupindia);

	/**
	 * Returns the incubator of this sbi start up.
	 *
	 * @return the incubator of this sbi start up
	 */
	@AutoEscape
	public String getIncubator();

	/**
	 * Sets the incubator of this sbi start up.
	 *
	 * @param incubator the incubator of this sbi start up
	 */
	public void setIncubator(String incubator);

	/**
	 * Returns the status of this sbi start up.
	 *
	 * @return the status of this sbi start up
	 */
	@AutoEscape
	public String getStatus();

	/**
	 * Sets the status of this sbi start up.
	 *
	 * @param status the status of this sbi start up
	 */
	public void setStatus(String status);

	/**
	 * Returns the flag of this sbi start up.
	 *
	 * @return the flag of this sbi start up
	 */
	public boolean getFlag();

	/**
	 * Returns <code>true</code> if this sbi start up is flag.
	 *
	 * @return <code>true</code> if this sbi start up is flag; <code>false</code> otherwise
	 */
	public boolean isFlag();

	/**
	 * Sets whether this sbi start up is flag.
	 *
	 * @param flag the flag of this sbi start up
	 */
	public void setFlag(boolean flag);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(SbiStartUp sbiStartUp);

	public int hashCode();

	public CacheModel<SbiStartUp> toCacheModel();

	public SbiStartUp toEscapedModel();

	public SbiStartUp toUnescapedModel();

	public String toString();

	public String toXmlString();
}