create table SbiStartUp_CapitalInf (
	InfRefId LONG not null primary key,
	createDate DATE null,
	modifiedDate DATE null,
	RegNum VARCHAR(75) null,
	cp_promoters_name VARCHAR(75) null,
	cp_promoters_address VARCHAR(75) null,
	cp_promoters_amount VARCHAR(75) null
);

create table SbiStartUp_ResumeDtls (
	ResumeId LONG not null primary key,
	createDate DATE null,
	modifiedDate DATE null,
	RegNum VARCHAR(75) null,
	Name VARCHAR(75) null,
	Email VARCHAR(75) null,
	Mnumber VARCHAR(75) null,
	Dob DATE null,
	address_line_1 VARCHAR(75) null,
	address_line_2 VARCHAR(75) null,
	address_landmark VARCHAR(75) null,
	address_city VARCHAR(75) null,
	address_pin VARCHAR(75) null,
	address_state VARCHAR(75) null,
	perm_address_line_1 VARCHAR(75) null,
	perm_address_line_2 VARCHAR(75) null,
	perm_address_landmark VARCHAR(75) null,
	perm_address_city VARCHAR(75) null,
	perm_address_pin VARCHAR(75) null,
	perm_address_state VARCHAR(75) null,
	Pan VARCHAR(75) null,
	AadharNum VARCHAR(75) null,
	CarrerAspect VARCHAR(75) null,
	KeyITSkill VARCHAR(75) null,
	CertfTra VARCHAR(75) null,
	EmpyHistory VARCHAR(75) null,
	CoreComp VARCHAR(75) null,
	Accomplishment VARCHAR(75) null,
	Academics VARCHAR(75) null,
	status VARCHAR(75) null,
	flag BOOLEAN,
	indexno VARCHAR(75) null
);

create table SbiStartUp_SbiStartUp (
	regnum VARCHAR(75) not null primary key,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	registered_name VARCHAR(75) null,
	date_of_establishment DATE null,
	constitution VARCHAR(75) null,
	address_line_1 VARCHAR(75) null,
	address_line_2 VARCHAR(75) null,
	address_landmark VARCHAR(75) null,
	address_city VARCHAR(75) null,
	address_pin VARCHAR(75) null,
	address_state VARCHAR(75) null,
	corporate_email VARCHAR(75) null,
	corporate_website VARCHAR(75) null,
	initial_founders VARCHAR(75) null,
	current_promoters_name VARCHAR(75) null,
	noofemp VARCHAR(75) null,
	description_of_product VARCHAR(75) null,
	initial_capital VARCHAR(75) null,
	monetary_value VARCHAR(75) null,
	business_model VARCHAR(75) null,
	current_capital VARCHAR(75) null,
	capital_infusion VARCHAR(75) null,
	Loans_availed VARCHAR(75) null,
	valuer_name VARCHAR(75) null,
	valuation_date DATE null,
	valuation_amount_rs VARCHAR(75) null,
	loan_avail_source VARCHAR(75) null,
	loan_avail_rs VARCHAR(75) null,
	gross_revenue_year1 VARCHAR(75) null,
	gross_revenue_rs1 VARCHAR(75) null,
	gross_revenue_year2 VARCHAR(75) null,
	gross_revenue_rs2 VARCHAR(75) null,
	gross_revenue_year3 VARCHAR(75) null,
	gross_revenue_rs3 VARCHAR(75) null,
	ebidta_year1 VARCHAR(75) null,
	ebidta_rs1 VARCHAR(75) null,
	ebidta_year2 VARCHAR(75) null,
	ebidta_rs2 VARCHAR(75) null,
	ebidta_year3 VARCHAR(75) null,
	ebidta_rs3 VARCHAR(75) null,
	gross_revenue_projected_year1 VARCHAR(75) null,
	projected_revenue_rs1 VARCHAR(75) null,
	gross_revenue_projected_year2 VARCHAR(75) null,
	projected_revenue_rs2 VARCHAR(75) null,
	gross_revenue_projected_year3 VARCHAR(75) null,
	projected_revenue_rs3 VARCHAR(75) null,
	projected_ebidta_year1 VARCHAR(75) null,
	projected_ebidta_rs1 VARCHAR(75) null,
	projected_ebidta_year2 VARCHAR(75) null,
	projected_ebidta_rs2 VARCHAR(75) null,
	projected_ebidta_year3 VARCHAR(75) null,
	projected_ebidta_rs3 VARCHAR(75) null,
	projected_net_profit_year1 VARCHAR(75) null,
	projected_net_profit_rs1 VARCHAR(75) null,
	projected_net_profit_year2 VARCHAR(75) null,
	projected_net_profit_rs2 VARCHAR(75) null,
	projected_net_profit_year3 VARCHAR(75) null,
	projected_net_profit_rs3 VARCHAR(75) null,
	net_profit_year1 VARCHAR(75) null,
	net_profit_rs1 VARCHAR(75) null,
	net_profit_year2 VARCHAR(75) null,
	net_profit_rs2 VARCHAR(75) null,
	net_profit_year3 VARCHAR(75) null,
	net_profit_rs3 VARCHAR(75) null,
	financial_bank_engagement VARCHAR(75) null,
	financial_assistance VARCHAR(75) null,
	financial_assi_purp VARCHAR(75) null,
	agreeable_process VARCHAR(75) null,
	gsr_department VARCHAR(75) null,
	startupindia VARCHAR(75) null,
	incubator VARCHAR(75) null,
	status VARCHAR(75) null,
	flag BOOLEAN
);